#!/bin/bash
#kasutaja loomine
kasutaja=$1
public=/home/$kasutaja/public
#
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 Kasutajanimi"

elif [ ! -d $public ]; then
	mkdir $public
	chmod -R 751 $public
	chown -R $kasutaja:www-data $public
	sed -i 's/public_html/public/g' /etc/apache2/mods-available/userdir.conf 
	a2enmod userdir
service apache2 restart

else
	echo "Kataloog $public on juba olemas"
	echo "Kontrollin õigusi"
if [ "stat -c "%a" $public" != 751 ]; then
	echo " õigused valed"
	chmod -R 751 $public
	chown -R $kasutaja:www-data $public
	echo "õigused õiged"
if [ $? -eq 0 ];
then
echo "Kaust on õige"
else
echo "probleem veebilehe loomisel"
echo "Veakood: $?"
fi
fi
fi
