#!/bin/bash
#kasutaja lisamine
#
#
#
if [ $# -ne 1 ]; then
	echo "kasutajajuhend: $0 kasutajanimi"
else
kasutajanimi=$1
useradd $kasutajanimi -m -s /bin/bash

if [ $? -eq 0 ]; then
	echo "kasutaja nimega $kasutajanimi on listaud"
	cat /etc/passwd | grep $kasutajanimi
	ls -la /home/$kasutajanimi
else
	echo "probleem$kasutajanimi lisamisega"
	echo "probleem"
fi
fi
