#!/bin/bash
#
#
#
#php installeerimine

sudo apt --assume-yes update
sudo apt --assume-yes upgrade
	if [ "dpkg-query -W -f='${Status}' php | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' libapache2-mod-php | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' php-mcrypt | grep -c "ok installed"" == 1 ] && [ "dpkg-query -W -f='${Status}' php-mysql | grep -c "ok installed"" == 1 ] ; then
echo "PHP on juba olemas"
        exit
echo "php-d paigaldatakse"
sudo apt --assume-yes install php libapache2-mod-php php-mcrypt php-mysql
echo "php on paigaldatud"
		fi
