#!/bin/bash
sudo apt --assume-yes update
sudo apt --assume-yes upgrade
if [ "dpkg-query -W -f='${Status}' apache2 | grep -c "ok installed"" == 1 ]; then
echo "apache on juba olemas"
exit
else
echo "apache installitakse"
sudo apt --assume-yes install apache2
echo "apache installitud"
fi
