#!/bin/bash
#
#
#
#
sudo apt --assume-yes update
sudo apt --assume-yes upgrade
if [ "dpkg-query -W -f='${Status}' nginx | grep -c "ok installed"" == 1 ]; then
echo "nginx on juba olemas"
exit
else
echo "nginx installitakse"
sudo apt --assume-yes install nginx
echo "nginx installitud"
fi

#
#
#
#MYSQL installeerimine
sudo apt --assume-yes update
sudo apt --assume-yes upgrade
if [ "dpkg-query -W -f='${Status}' mysql | grep -c "ok installed"" == 1 ]; then
echo "mysql on juba olemas"
exit
else
echo "mysql installitakse"
sudo apt --assume-yes install mysql-server
mysql_secure_installation
echo "mysql on installitud"
	fi

#
#
#php installeerimine

sudo apt --assume-yes update
sudo apt --assume-yes upgrade
	if [ "dpkg-query -W -f='${Status}' php | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' libapache2-mod-php | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' php-mcrypt | grep -c "ok installed"" == 1 ] && [ "dpkg-query -W -f='${Status}' php-mysql | grep -c "ok installed"" == 1 ] ; then
echo "PHP on juba olemas"
        exit
echo "php-d paigaldatakse"
sudo apt --assume-yes install php libapache2-mod-php php-mcrypt php-mysql
echo "php on paigaldatud"
		fi


#
#
#phpmyadmin installeerimine
sudo apt --assume-yes update
sudo apt -assume-yes upgrade
if [ "dpkg-query -W -f='${Status}' phpmyadmin | grep -c "ok installed"" == 1 ] && [ "dpkg-query -W -f='${Status}' apache2 | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' mysql-server | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' libapache2-mod-php | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' php-mcrypt | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' php-mysql | grep -c "ok installed""  == 1 ]; then
echo "phpmyadmin on juba olemas"
exit
else
echo "installeerimine"
sudo apt --assume-yes install mysql-server php libapache2-mod-php php-mcrypt php-mysql phpmyadmin
mysql_secure_installation
echo "phpmyadmin on installitud"
fi

clear
echo "============================================"
echo "WordPress Install Script"
echo "============================================"
echo "Database nimi: "
read -e dbname
echo "Database kasutaja: "
read -e dbuser
echo "Database Password: "
read -s dbpass
echo "installeeri? (y/n)"
read -e run
if [ "$run" == n ] ; then
exit
else
echo "wordpressi installeeritakse"
#wp allalaadimine..
curl -O https://wordpress.org/latest.tar.gz
#wordpressi lahtipakkimine
tar -zxvf latest.tar.gz
#mine wordpressi kasuta
cd wordpress
cp -rf . ..
cd ..
rm -R wordpress
#tehakse wordpressi config
cp wp-config-sample.php wp-config.php
perl -pi -e "s/database_name_here/$dbname/g" wp-config.php
perl -pi -e "s/username_here/$dbuser/g" wp-config.php
perl -pi -e "s/password_here/$dbpass/g" wp-config.php

perl -i -pe'
  BEGIN {
    @chars = ("a" .. "z", "A" .. "Z", 0 .. 9);
    push @chars, split //, "!@#$%^&*()-_ []{}<>~\`+=,.;:/?|";
    sub salt { join "", map $chars[ rand @chars ], 1 .. 64 }
  }
  s/put your unique phrase here/salt()/ge
' wp-config.php

#muudetakse õigused
mkdir wp-content/uploads
chmod 775 wp-content/uploads
echo "Install on tehtud"
fi


