#!/bin/bash


sudo apt --assume-yes update
sudo apt --assume-yes upgrade
	if [ "dpkg-query -W -f='${Status}' php | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' libapache2-mod-php | grep -c "ok installed""  == 1 ] && [ "dpkg-query -W -f='${Status}' php-mcrypt | grep -c "ok installed"" == 1 ] && [ "dpkg-query -W -f='${Status}' php-mysql | grep -c "ok installed"" == 1 ] ; then
                echo "PHP ja kõik vajalikud osad on süsteemis olemas"
                exit
        else
        echo "PHP paigaldmine..."
        sudo apt --assume-yes install php libapache2-mod-php php-mcrypt php-mysql
        echo "PHP ja vajalikud osad paigaltatud"
        fi
