#!/bin/bash
#
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 kasutajanimi"
else
kasutajanimi=$1
mkdir /home/$kasutajanimi/public
chmod -R 751 /home/$kasutajanimi/public
sed -i 's/public_html/public/g' /etc/apache2/mods-available/userdir.conf
a2enmod userdir
service apache2 restart

fi

